import:
  - "vendor/unleashedtech/deployer-recipes/dev/todo.php"

config:
  git_repo_user: 'git'
  repository: '{{git_repo_user}}@{{git_repo_domain}}:{{application}}/{{app_type}}.git'
  staging_host: '{{application}}-staging'
  staging_domain: '{{application}}.{{staging_tld}}'
  app: '{{repo}}/{{app_dir_name}}'
  app_dir_name: 'web'
  backups: '{{deploy_path}}/shared/backups'
  bin: '{{repo}}/vendor/bin'
  repo: '/var/www'

hosts:
  staging:
    deploy_path: '/srv/www/{{staging_domain}}'
    hostname: '{{staging_host}}'
    repo: '{{deploy_path}}/current'
    stage: 'staging'

after:
  deploy:failed: deploy:unlock
