import:
  - "vendor/unleashedtech/deployer-recipes/dev/todo.php"

# Global config.
config:
  app_path: '{{release}}/{{app_directory_name}}'
  app_directory_name: 'web'
  backups: '{{deploy_path}}/shared/backups'
  bin: '{{release}}/vendor/bin'
  repository: '{{repository_user}}@{{repository_domain}}:{{application}}/{{app_type}}.git'
  repository_domain: 'github.com'
  repository_user: 'git'
  staging_domain: '{{application}}.{{staging_tld}}'
  staging_hostname: '{{application}}-staging'
  staging_tld: 'example.com'

# Host-specific config.
hosts:
  staging:
    deploy_path: '/srv/www/{{staging_domain}}'
    hostname: '{{staging_hostname}}'
    release: '{{deploy_path}}/current'
    stage: 'staging'

after:
  deploy:failed: deploy:unlock
