import:
    - "vendor/unleashedtech/deployer-recipes/dev/todo.php"

# Global config.
config:
    app_path: '{{release}}/{{app_directory_name}}'
    app_directory_name: 'web'
    backups: '{{deploy_path}}/shared/backups'
    bin: '{{release}}/vendor/bin'
    composer_install_options: '--verbose --prefer-dist --no-progress --no-interaction --no-dev --no-scripts --optimize-autoloader'
    deploy_root: '/srv/www'
    local_backups: 'backups'
    local_database_backups: '{{local_backups}}/databases'
    local_file_backups: '{{local_backups}}/files'
    repository: '{{repository_user}}@{{repository_domain}}:{{repository_namespace}}/{{repository_project}}.git'
    repository_domain: 'github.com'
    repository_namespace: '{{application}}'
    repository_project: '{{app_type}}'
    repository_user: 'git'

    # Dev "stage" global variables.
    dev_deploy_path: '{{deploy_root}}/{{dev_host}}'
    dev_host: '{{application}}.{{dev_domain}}'
    dev_name: '{{application}}-dev'
    dev_domain: 'dev.example'

    # Staging "stage" global variables.
    staging_deploy_path: '{{deploy_root}}/{{staging_host}}'
    staging_host: '{{application}}.{{staging_domain}}'
    staging_name: '{{application}}-staging'
    staging_domain: 'staging.example'

    # Production "stage" global variables.
    production_deploy_path: '{{deploy_root}}/{{production_host}}'
    production_host: '{{application}}.{{production_domain}}'
    production_name: '{{application}}-production'
    production_domain: 'production.example'

# Host-specific config.
hosts:
    dev:
        deploy_path: '{{dev_deploy_path}}'
        hostname: '{{dev_name}}'
        release: '{{deploy_path}}/current'
        stage: 'dev'
    staging:
        deploy_path: '{{staging_deploy_path}}'
        hostname: '{{staging_name}}'
        release: '{{deploy_path}}/current'
        stage: 'staging'
    production:
        deploy_path: '{{production_deploy_path}}'
        # TODO: revise config to allow for multiple production host names
        hostname: '{{production_name}}'
        release: '{{deploy_path}}/current'
        stage: 'production'

after:
    deploy:failed: deploy:unlock
