---
import:
  - vendor/unleashedtech/deployer-recipes/cms/magento/maintenance/disable.yml
  - vendor/unleashedtech/deployer-recipes/cms/magento/maintenance/enable.yml

tasks:
    cms:magento:config:import:
        - run: 'cd {{release_or_current_path}}/{{app_directory_name}} && {{mage}} app:config:status'
        - run: cms:magento:maintenance:enable
        - run: 'cd {{release_or_current_path}}/{{app_directory_name}} && {{mage}} app:config:import --no-interaction'
        - run: cms:magento:maintenance:disable
